feat (SRE-portal): Client setup for webterminal
operate-first/service-catalog pull request #206
Opened 2023-01-12 12:16 UTC by mimotej

This PR adds REST requests to initialize devworkspace and adds subprotocols which are then send to the proxy. These subprotocols contain basic information so that proxy knows for which pod to finish initialization and connect to it.
This PR should be discussed simultaneously with PR that introduces websocket proxy

2023-01-16 15:42 UTC, tumido requested changes
just few nits, otherwise lgtm :+1:

2023-01-16 15:42 UTC, tumido commented on plugins/web-terminal/src/components/TerminalComponent/utils/requests.ts
> +const workspace = {
Please uppercase all global consts. https://typescript-eslint.io/rules/naming-convention/

2023-01-16 15:42 UTC, tumido commented on plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
> +    const cluster = formData.cluster;
```suggestion
    const { token, cluster } = formData;
```

2023-01-16 15:42 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please assign durandom for approval by writing `/assign @durandom` in a comment. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fservice-catalog).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/service-catalog/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2023-01-17 11:06 UTC, sesheta commented
@mimotej: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 585a713f5f8d7a0f8c7c76dc7a9c749a26fcb1a6 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_service-catalog/206/pre-commit/1615304488459964416) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=service-catalog&pr=206). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Amimotej). Please help us and [open an issue](https://github.com/operate-first/service-catalog/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-01-17 11:33 UTC, mimotej commented on plugins/web-terminal/src/components/TerminalComponent/utils/requests.ts
> +const workspace = {
Resolved

2023-01-23 13:15 UTC, tumido approved these changes
/lgtm
/approve

2023-01-23 13:16 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/service-catalog/pull/206#pullrequestreview-1265573316" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fservice-catalog).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/service-catalog/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-01-23 13:17 UTC, merged