feat(webterminal-plugin): Add tests for webterminal plugin
operate-first/service-catalog pull request #227
Opened 2023-04-12 07:03 UTC by mimotej

SSIA

2023-04-12 07:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please assign durandom for approval by writing `/assign @durandom` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fservice-catalog).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/service-catalog/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2023-04-18 06:11 UTC, mimotej commented
/cc @tumido

2023-04-20 13:00 UTC, tumido requested changes
Just a nit. Otherwise, LGTM 👍 This looks great! 🙂

2023-04-20 13:06 UTC, mimotej commented on plugins/web-terminal/src/components/TerminalComponent/mocks/createWorkspace.json
Done. :)

2023-04-25 08:47 UTC, tumido approved these changes
/lgtm
/approve

2023-04-25 08:47 UTC, merged