feat: Add ArgoCD plugin to service catalog
operate-first/service-catalog pull request #32
Opened 2022-07-11 06:52 UTC by mimotej

This PR adds ArgoCD plugin to the service page. Plugin shows name, sync status, health and when it was last synced:
![image](https://user-images.githubusercontent.com/47832967/178205581-37746b54-9365-44a2-ba87-8ac5c2df2ac3.png)

2022-07-11 06:52 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fservice-catalog).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/service-catalog/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2022-07-11 09:59 UTC, tumido requested changes
Couple of changes required. I suspect the deployment manifests were not tested because they are not kubernetes compatible. :stuck_out_tongue:  See inline comments.

2022-07-11 10:23 UTC, mimotej commented on app-config.yaml
> +    secure: false
Resolved in latest commit.

2022-07-11 10:23 UTC, mimotej commented on manifests/base/deployment.yaml
> +                key: ARGOCD_AUTH_TOKEN
Resolved in latest commit.

2022-07-13 11:14 UTC, tumido approved these changes
/lgtm
/approve

2022-07-13 11:14 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/service-catalog/pull/32#pullrequestreview-1037188774" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fservice-catalog).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/service-catalog/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-07-13 11:17 UTC, merged